# Generated by Django 4.2.1 on 2023-07-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='sentence',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
