# Generated by Django 4.2.1 on 2023-10-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_knowledge_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='en_ru',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='ru_en',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Knowledge',
        ),
    ]
