# Generated by Django 4.2.1 on 2024-09-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studyinglanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyinglanguage',
            name='name',
            field=models.CharField(choices=[('en', 'English'), ('bg', 'Bulgarian')], max_length=255),
        ),
    ]
