# Generated by Django 4.2.1 on 2024-09-11 16:13

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_studyinglanguage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='en_ru',
            new_name='know_native_to_studying',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='ru_en',
            new_name='know_studying_to_native',
        ),
        migrations.AddField(
            model_name='word',
            name='studying_lang',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='core.studyinglanguage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studyinglanguage',
            name='name',
            field=models.CharField(choices=[('en', 'English'), ('bg', 'Bulgarian')], max_length=255, unique=True, validators=[core.models.empty_validator]),
        ),
    ]
