# Generated by Django 4.2.1 on 2024-10-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gttsaudio',
            name='use',
            field=models.CharField(choices=[('word', 'for_word'), ('sentence', 'for_sentence')], default='word', max_length=255),
            preserve_default=False,
        ),
    ]
