# Generated by Django 4.2.1 on 2024-12-06 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_gttsaudio_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='reset_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 18, 58, 59, 695150)),
        ),
        migrations.AddField(
            model_name='word',
            name='stage',
            field=models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('three_month', 'three_month'), ('half_year', 'half_year')], default=('day', 'day'), max_length=100),
        ),
    ]
