# Generated by Django 4.2.1 on 2024-12-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_word_reset_date_word_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='reset_date',
        ),
        migrations.AddField(
            model_name='word',
            name='correct_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
